version: '3.8'
services:
  bot:
    build: .
    volumes:
      - ./bot:/usr/src/app:rw
    environment:
      - TOKEN=${TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - TEST_CHANNEL_ID=${TEST_CHANNEL_ID}
      - TZ=Asia/Tokyo
    command: ["python3", "main.py"]
    tty: true
