version: '3.8'
services:
  bot:
    build: .
    volumes:
      - ./bot:/usr/src/app:rw
    environment:
      - TOKEN=${TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
    command: ["python3", "card-mining.py"]
    tty: true
